CUSTOMER_ID = "apapkovskiyID"
COGNITO_CLIENT_ID = "6hmp262n9v8i8tu3368ovuj0ud"
AUTH_USERNAME = ""
AUTH_PASSWORD = ""
AUTH_URL = "https://cognito-idp.eu-west-1.amazonaws.com"
BASE_URL = "https://b5huyql8sh.execute-api.eu-west-1.amazonaws.com/latest"
